# -*- coding: utf-8 -*-
"""HIJAZ bot — 5 tilli tarjimalar: O'zbek, Rus, Ingliz, Arab, Turk"""

TR = {
    # ==================== O'ZBEK ====================
    "uz": {
        "lang_name": "🇺🇿 O'zbek",
        "welcome": (
            "🕋 *HIJAZ — Saudiya mehmonxona broni*\n\n"
            "Assalomu alaykum! Makka va Madinada mehmonxona bron qilish "
            "hamda transfer xizmati uchun so'rov qoldiring.\n\n"
            "Quyidagidan tanlang 👇"
        ),
        "menu_booking": "🏨 Bron so'rovi",
        "menu_contact": "📞 Bog'lanish",
        "menu_info": "ℹ️ Ma'lumot",
        "menu_lang": "🌐 Tilni o'zgartirish",
        "choose_service": "Sizga nima kerak?",
        "svc_hotel": "🏨 Mehmonxona",
        "svc_transfer": "🚗 Transfer",
        "svc_both": "🏨+🚗 Ikkalasi",
        "choose_city": "Qaysi shahar?",
        "city_makkah": "🕋 Makka",
        "city_madinah": "🕌 Madina",
        "city_both": "Ikkalasi",
        "hotel_stars": "Mehmonxona darajasi?",
        "stars_any": "Farqi yo'q",
        "meal": "Taomlanish turi?",
        "meal_ro": "Faqat yashash",
        "meal_bb": "Nonushta bilan",
        "meal_hb": "Yarim pansion",
        "meal_fb": "To'liq pansion",
        "guests": "Necha kishi? (raqam kiriting)",
        "room_count": "Nechta xona kerak? (raqam)",
        "room_type": "Xona turi (necha kishilik)?",
        "rt_single": "1 kishilik",
        "rt_double": "2 kishilik",
        "rt_triple": "3 kishilik",
        "rt_quad": "4 kishilik",
        "rt_mixed": "Aralash / farqi yo'q",
        "a_rooms": "Xonalar soni",
        "a_roomtype": "Xona turi",
        "checkin": "Kirish sanasi? (masalan: 15/08/2026)",
        "mk_checkin": "🕋 MAKKA — kirish sanasi? (masalan: 15/08/2026)",
        "mk_checkout": "🕋 MAKKA — chiqish sanasi? (masalan: 18/08/2026)",
        "md_checkin": "🕌 MADINA — kirish sanasi? (masalan: 18/08/2026)",
        "md_checkout": "🕌 MADINA — chiqish sanasi? (masalan: 21/08/2026)",
        "a_mk_dates": "Makka sanasi",
        "a_md_dates": "Madina sanasi",
        "checkout": "Chiqish sanasi? (masalan: 18/08/2026)",
        "budget": "Budjet (bir kecha uchun, $)? Bilmasangiz 'O'tkazish' bosing",
        "skip": "O'tkazish",
        "transfer_type": "Transfer turi?",
        "tr_airport": "✈️ Aeroport ↔ mehmonxona",
        "tr_intercity": "🚙 Shaharlararo (Makka ↔ Madina)",
        "tr_ziyorat": "🕌 Ziyorat / ekskursiya",
        "transfer_route": "Yo'nalishni yozing (masalan: Jidda aeroport → Makka)",
        "transfer_date": "Transfer sanasi? (masalan: 15/08/2026)",
        "pax": "Necha yo'lovchi? (raqam)",
        "phone": "📱 Telefon raqamingiz? (tugmani bosing yoki yozing)",
        "phone_btn": "📱 Raqamni yuborish",
        "name": "Ismingiz?",
                "confirm_title": "📋 So'rovingizni tekshiring:",
        "confirm_ask": "Hammasi to'g'rimi?",
        "btn_confirm": "✅ Tasdiqlash",
        "btn_cancel": "❌ Bekor qilish",
        "cancelled": "❌ So'rov bekor qilindi. Qaytadan boshlash uchun menyudan foydalaning.",
        "c_service": "Xizmat",
        "c_hotel": "Mehmonxona",
        "c_transfer": "Transfer",
        "req_no": "So'rov raqami",
        "route_other": "✏️ Boshqa (ozim yozaman)",
        "transfer_route_manual": "Yonalishni yozing (masalan: Jidda aeroport → Makka hotel):",
        "car_q": "🚗 Qanday avtomobil kerak? (ixtiyoriy)\n\nTanlang yoki «Farqi yoq» bosing — operatorimiz yolovchilar soniga mos mashina taklif qiladi.",
        "car_any": "✔️ Farqi yoq / operator tanlasin",
        "a_car": "Avtomobil",
        "hotel_q": "🏨 Aniq mehmonxona tanlaysizmi? (ixtiyoriy)\n\nRoyxatdan tanlang yoki «Farqi yoq» bosing — operatorimiz eng mos variantni taklif qiladi.",
        "hotel_any": "✔️ Farqi yoq / operator tavsiya qilsin",
        "a_hotel_sel": "Tanlangan mehmonxona",
        "done": (
            "✅ So'rovingiz qabul qilindi!\n\nRahmat! HIJAZ jamoasi tez orada siz bilan bog'lanadi va barcha savollaringizga javob beradi.\n\n💰 Narx va to'liq ma'lumotni operatorimiz shaxsan aytadi.\n⏱ Odatda 1 soat ichida javob beramiz (ish vaqtida).\n\nSabringiz uchun rahmat! 🕋"
        ),
        "contact_txt": "📞 HIJAZ bilan bog'lanish\n\nQuyidagi tugmalar orqali biz bilan tez bog'laning. Savollaringizga jamoamiz javob beradi.",
        "btn_call": "📞 Qo'ng'iroq",
        "btn_tg": "✈️ Telegram",
        "btn_wa": "💬 WhatsApp",
        "btn_ig": "📷 Instagram",
        "info_txt": (
            "ℹ️ *HIJAZ haqida*\n\n"
            "HIJAZ — Makka va Madinada ishonchli mehmonxona broni va transfer xizmati.\n\n"
            "• Haramga yaqin mehmonxonalar\n• Aeroport va shaharlararo transfer\n"
            "• Ziyorat uyushtirish\n• Qulay narxlar\n\n"
            "Bron uchun 🏨 tugmasini bosing."
        ),
        "choose_lang": "Tilni tanlang / Выберите язык / Choose language:",
        "invalid_num": "Iltimos, raqam kiriting.",
        "back": "⬅️ Orqaga",
        # admin so'rov teglari
        "a_new": "🔔 YANGI SO'ROV",
        "a_type": "Turi",
        "a_hotel": "Mehmonxona",
        "a_transfer": "Transfer",
        "a_city": "Shahar",
        "a_stars": "Daraja",
        "a_meal": "Taomlanish",
        "a_guests": "Mehmonlar",
        "a_dates": "Sana",
        "a_budget": "Budjet",
        "a_trtype": "Transfer turi",
        "a_route": "Yo'nalish",
        "a_pax": "Yo'lovchilar",
        "a_phone": "Telefon",
        "a_name": "Ism",
        "a_lang": "Til",
        "a_user": "Foydalanuvchi",
        "nights": "kecha",
    },
    # ==================== РУССКИЙ ====================
    "ru": {
        "lang_name": "🇷🇺 Русский",
        "welcome": (
            "🕋 *HIJAZ — Бронирование отелей в Саудовской Аравии*\n\n"
            "Ассаляму алейкум! Оставьте заявку на бронирование отеля в Мекке "
            "и Медине, а также на трансфер.\n\n"
            "Выберите ниже 👇"
        ),
        "menu_booking": "🏨 Оставить заявку",
        "menu_contact": "📞 Контакты",
        "menu_info": "ℹ️ Информация",
        "menu_lang": "🌐 Сменить язык",
        "choose_service": "Что вам нужно?",
        "svc_hotel": "🏨 Отель",
        "svc_transfer": "🚗 Трансфер",
        "svc_both": "🏨+🚗 Оба",
        "choose_city": "Какой город?",
        "city_makkah": "🕋 Мекка",
        "city_madinah": "🕌 Медина",
        "city_both": "Оба",
        "hotel_stars": "Категория отеля?",
        "stars_any": "Не важно",
        "meal": "Тип питания?",
        "meal_ro": "Только проживание",
        "meal_bb": "Завтрак",
        "meal_hb": "Полупансион",
        "meal_fb": "Полный пансион",
        "guests": "Сколько человек? (введите число)",
        "room_count": "Сколько номеров нужно? (число)",
        "room_type": "Тип номера (на сколько человек)?",
        "rt_single": "1-местный",
        "rt_double": "2-местный",
        "rt_triple": "3-местный",
        "rt_quad": "4-местный",
        "rt_mixed": "Смешанный / не важно",
        "a_rooms": "Кол-во номеров",
        "a_roomtype": "Тип номера",
        "checkin": "Дата заезда? (например: 15/08/2026)",
        "mk_checkin": "🕋 МЕККА — дата заезда? (например: 15/08/2026)",
        "mk_checkout": "🕋 МЕККА — дата выезда? (например: 18/08/2026)",
        "md_checkin": "🕌 МЕДИНА — дата заезда? (например: 18/08/2026)",
        "md_checkout": "🕌 МЕДИНА — дата выезда? (например: 21/08/2026)",
        "a_mk_dates": "Даты Мекка",
        "a_md_dates": "Даты Медина",
        "checkout": "Дата выезда? (например: 18/08/2026)",
        "budget": "Бюджет (за ночь, $)? Если не знаете — нажмите 'Пропустить'",
        "skip": "Пропустить",
        "transfer_type": "Тип трансфера?",
        "tr_airport": "✈️ Аэропорт ↔ отель",
        "tr_intercity": "🚙 Между городами (Мекка ↔ Медина)",
        "tr_ziyorat": "🕌 Зиярат / экскурсия",
        "transfer_route": "Напишите маршрут (например: аэропорт Джидда → Мекка)",
        "transfer_date": "Дата трансфера? (например: 15/08/2026)",
        "pax": "Сколько пассажиров? (число)",
        "phone": "📱 Ваш номер телефона? (нажмите кнопку или напишите)",
        "phone_btn": "📱 Отправить номер",
        "name": "Ваше имя?",
                "confirm_title": "📋 Проверьте вашу заявку:",
        "confirm_ask": "Всё верно?",
        "btn_confirm": "✅ Подтвердить",
        "btn_cancel": "❌ Отменить",
        "cancelled": "❌ Заявка отменена. Используйте меню, чтобы начать заново.",
        "c_service": "Услуга",
        "c_hotel": "Отель",
        "c_transfer": "Трансфер",
        "req_no": "Номер заявки",
        "route_other": "✏️ Другое (напишу сам)",
        "transfer_route_manual": "Напишите маршрут (например: аэропорт Джидда → отель Макка):",
        "car_q": "🚗 Какой автомобиль нужен? (необязательно)\n\nВыберите или нажмите «Не важно» — оператор подберёт подходящий транспорт.",
        "car_any": "✔️ Не важно / оператор подберёт",
        "a_car": "Автомобиль",
        "hotel_q": "🏨 Выбрать конкретный отель? (необязательно)\n\nВыберите из списка или нажмите «Не важно».",
        "hotel_any": "✔️ Не важно / оператор предложит",
        "a_hotel_sel": "Выбранный отель",
        "done": (
            "✅ Ваша заявка принята!\n\nСпасибо! Команда HIJAZ скоро свяжется с вами и ответит на все вопросы.\n\n💰 Цену и полную информацию сообщит наш оператор лично.\n⏱ Обычно отвечаем в течение 1 часа (в рабочее время).\n\nСпасибо за ожидание! 🕋"
        ),
        "contact_txt": "📞 Связь с HIJAZ\n\nСвяжитесь с нами через кнопки ниже. Наша команда ответит на ваши вопросы.",
        "btn_call": "📞 Позвонить",
        "btn_tg": "✈️ Telegram",
        "btn_wa": "💬 WhatsApp",
        "btn_ig": "📷 Instagram",
        "info_txt": (
            "ℹ️ *О HIJAZ*\n\n"
            "HIJAZ — надёжное бронирование отелей и трансфер в Мекке и Медине.\n\n"
            "• Отели рядом с Харамом\n• Аэропорт и междугородний трансфер\n"
            "• Организация зиярата\n• Удобные цены\n\n"
            "Для заявки нажмите 🏨."
        ),
        "choose_lang": "Tilni tanlang / Выберите язык / Choose language:",
        "invalid_num": "Пожалуйста, введите число.",
        "back": "⬅️ Назад",
        "a_new": "🔔 НОВАЯ ЗАЯВКА",
        "a_type": "Тип",
        "a_hotel": "Отель",
        "a_transfer": "Трансфер",
        "a_city": "Город",
        "a_stars": "Категория",
        "a_meal": "Питание",
        "a_guests": "Гости",
        "a_dates": "Даты",
        "a_budget": "Бюджет",
        "a_trtype": "Тип трансфера",
        "a_route": "Маршрут",
        "a_pax": "Пассажиры",
        "a_phone": "Телефон",
        "a_name": "Имя",
        "a_lang": "Язык",
        "a_user": "Пользователь",
        "nights": "ночей",
    },
    # ==================== ENGLISH ====================
    "en": {
        "lang_name": "🇬🇧 English",
        "welcome": (
            "🕋 *HIJAZ — Saudi Hotel Booking*\n\n"
            "Assalamu alaikum! Send a request to book a hotel in Makkah "
            "and Madinah, and for transfer service.\n\n"
            "Please choose below 👇"
        ),
        "menu_booking": "🏨 Booking Request",
        "menu_contact": "📞 Contact",
        "menu_info": "ℹ️ Info",
        "menu_lang": "🌐 Change language",
        "choose_service": "What do you need?",
        "svc_hotel": "🏨 Hotel",
        "svc_transfer": "🚗 Transfer",
        "svc_both": "🏨+🚗 Both",
        "choose_city": "Which city?",
        "city_makkah": "🕋 Makkah",
        "city_madinah": "🕌 Madinah",
        "city_both": "Both",
        "hotel_stars": "Hotel category?",
        "stars_any": "Any",
        "meal": "Meal plan?",
        "meal_ro": "Room only",
        "meal_bb": "Bed & Breakfast",
        "meal_hb": "Half board",
        "meal_fb": "Full board",
        "guests": "How many guests? (enter a number)",
        "room_count": "How many rooms? (number)",
        "room_type": "Room type (for how many)?",
        "rt_single": "Single (1)",
        "rt_double": "Double (2)",
        "rt_triple": "Triple (3)",
        "rt_quad": "Quad (4)",
        "rt_mixed": "Mixed / any",
        "a_rooms": "Rooms",
        "a_roomtype": "Room type",
        "checkin": "Check-in date? (e.g. 15/08/2026)",
        "mk_checkin": "🕋 MAKKAH — check-in date? (e.g. 15/08/2026)",
        "mk_checkout": "🕋 MAKKAH — check-out date? (e.g. 18/08/2026)",
        "md_checkin": "🕌 MADINAH — check-in date? (e.g. 18/08/2026)",
        "md_checkout": "🕌 MADINAH — check-out date? (e.g. 21/08/2026)",
        "a_mk_dates": "Makkah dates",
        "a_md_dates": "Madinah dates",
        "checkout": "Check-out date? (e.g. 18/08/2026)",
        "budget": "Budget (per night, $)? If unknown, press 'Skip'",
        "skip": "Skip",
        "transfer_type": "Transfer type?",
        "tr_airport": "✈️ Airport ↔ hotel",
        "tr_intercity": "🚙 Intercity (Makkah ↔ Madinah)",
        "tr_ziyorat": "🕌 Ziyarat / excursion",
        "transfer_route": "Write the route (e.g. Jeddah airport → Makkah)",
        "transfer_date": "Transfer date? (e.g. 15/08/2026)",
        "pax": "How many passengers? (number)",
        "phone": "📱 Your phone number? (press button or type)",
        "phone_btn": "📱 Send number",
        "name": "Your name?",
                "confirm_title": "📋 Please review your request:",
        "confirm_ask": "Is everything correct?",
        "btn_confirm": "✅ Confirm",
        "btn_cancel": "❌ Cancel",
        "cancelled": "❌ Request cancelled. Use the menu to start again.",
        "c_service": "Service",
        "c_hotel": "Hotel",
        "c_transfer": "Transfer",
        "req_no": "Request number",
        "route_other": "✏️ Other (I will type)",
        "transfer_route_manual": "Type the route (e.g. Jeddah airport → Makkah hotel):",
        "car_q": "🚗 Which vehicle do you need? (optional)\n\nPick one or tap «No preference» — our operator will match it to your group size.",
        "car_any": "✔️ No preference / operator decides",
        "a_car": "Vehicle",
        "hotel_q": "🏨 Choose a specific hotel? (optional)\n\nPick from the list or tap «No preference».",
        "hotel_any": "✔️ No preference / operator suggests",
        "a_hotel_sel": "Selected hotel",
        "done": (
            "✅ Your request has been received!\n\nThank you! The HIJAZ team will contact you soon and answer all your questions.\n\n💰 The price and full details will be shared by our operator personally.\n⏱ We usually reply within 1 hour (during working hours).\n\nThank you for your patience! 🕋"
        ),
        "contact_txt": "📞 Contact HIJAZ\n\nReach us quickly via the buttons below. Our team will answer your questions.",
        "btn_call": "📞 Call",
        "btn_tg": "✈️ Telegram",
        "btn_wa": "💬 WhatsApp",
        "btn_ig": "📷 Instagram",
        "info_txt": (
            "ℹ️ *About HIJAZ*\n\n"
            "HIJAZ — reliable hotel booking and transfer in Makkah and Madinah.\n\n"
            "• Hotels near the Haram\n• Airport & intercity transfer\n"
            "• Ziyarat arrangement\n• Convenient prices\n\n"
            "Press 🏨 to make a request."
        ),
        "choose_lang": "Tilni tanlang / Выберите язык / Choose language:",
        "invalid_num": "Please enter a number.",
        "back": "⬅️ Back",
        "a_new": "🔔 NEW REQUEST",
        "a_type": "Type",
        "a_hotel": "Hotel",
        "a_transfer": "Transfer",
        "a_city": "City",
        "a_stars": "Category",
        "a_meal": "Meal",
        "a_guests": "Guests",
        "a_dates": "Dates",
        "a_budget": "Budget",
        "a_trtype": "Transfer type",
        "a_route": "Route",
        "a_pax": "Passengers",
        "a_phone": "Phone",
        "a_name": "Name",
        "a_lang": "Language",
        "a_user": "User",
        "nights": "nights",
    },
    # ==================== العربية ====================
    "ar": {
        "lang_name": "🇸🇦 العربية",
        "welcome": (
            "🕋 *حجاز — حجز الفنادق في السعودية*\n\n"
            "السلام عليكم! أرسل طلباً لحجز فندق في مكة والمدينة، وكذلك خدمة النقل.\n\n"
            "اختر من الأسفل 👇"
        ),
        "menu_booking": "🏨 طلب حجز",
        "menu_contact": "📞 تواصل",
        "menu_info": "ℹ️ معلومات",
        "menu_lang": "🌐 تغيير اللغة",
        "choose_service": "ماذا تحتاج؟",
        "svc_hotel": "🏨 فندق",
        "svc_transfer": "🚗 نقل",
        "svc_both": "🏨+🚗 كلاهما",
        "choose_city": "أي مدينة؟",
        "city_makkah": "🕋 مكة",
        "city_madinah": "🕌 المدينة",
        "city_both": "كلاهما",
        "hotel_stars": "فئة الفندق؟",
        "stars_any": "لا يهم",
        "meal": "نوع الوجبات؟",
        "meal_ro": "الإقامة فقط",
        "meal_bb": "مع الإفطار",
        "meal_hb": "نصف إقامة",
        "meal_fb": "إقامة كاملة",
        "guests": "كم عدد النزلاء؟ (أدخل رقماً)",
        "room_count": "كم عدد الغرف المطلوبة؟ (رقم)",
        "room_type": "نوع الغرفة (لكم شخص)؟",
        "rt_single": "فردية (1)",
        "rt_double": "مزدوجة (2)",
        "rt_triple": "ثلاثية (3)",
        "rt_quad": "رباعية (4)",
        "rt_mixed": "مختلط / لا يهم",
        "a_rooms": "عدد الغرف",
        "a_roomtype": "نوع الغرفة",
        "checkin": "تاريخ الوصول؟ (مثال: 15/08/2026)",
        "mk_checkin": "🕋 مكة — تاريخ الوصول؟ (مثال: 15/08/2026)",
        "mk_checkout": "🕋 مكة — تاريخ المغادرة؟ (مثال: 18/08/2026)",
        "md_checkin": "🕌 المدينة — تاريخ الوصول؟ (مثال: 18/08/2026)",
        "md_checkout": "🕌 المدينة — تاريخ المغادرة؟ (مثال: 21/08/2026)",
        "a_mk_dates": "تواريخ مكة",
        "a_md_dates": "تواريخ المدينة",
        "checkout": "تاريخ المغادرة؟ (مثال: 18/08/2026)",
        "budget": "الميزانية (لليلة، $)؟ إن لم تعرف اضغط 'تخطي'",
        "skip": "تخطي",
        "transfer_type": "نوع النقل؟",
        "tr_airport": "✈️ المطار ↔ الفندق",
        "tr_intercity": "🚙 بين المدن (مكة ↔ المدينة)",
        "tr_ziyorat": "🕌 زيارة / رحلة",
        "transfer_route": "اكتب المسار (مثال: مطار جدة → مكة)",
        "transfer_date": "تاريخ النقل؟ (مثال: 15/08/2026)",
        "pax": "كم عدد الركاب؟ (رقم)",
        "phone": "📱 رقم هاتفك؟ (اضغط الزر أو اكتب)",
        "phone_btn": "📱 إرسال الرقم",
        "name": "اسمك؟",
                "confirm_title": "📋 يرجى مراجعة طلبك:",
        "confirm_ask": "هل كل شيء صحيح؟",
        "btn_confirm": "✅ تأكيد",
        "btn_cancel": "❌ إلغاء",
        "cancelled": "❌ تم إلغاء الطلب. استخدم القائمة للبدء من جديد.",
        "c_service": "الخدمة",
        "c_hotel": "فندق",
        "c_transfer": "نقل",
        "req_no": "رقم الطلب",
        "route_other": "✏️ آخر (سأكتب)",
        "transfer_route_manual": "اكتب المسار (مثال: مطار جدة → فندق مكة):",
        "car_q": "🚗 ما السيارة التي تحتاجها؟ (اختياري)\n\nاختر أو اضغط «لا يهم» — سيختار موظفنا المركبة المناسبة.",
        "car_any": "✔️ لا يهم / يختار الموظف",
        "a_car": "المركبة",
        "hotel_q": "🏨 هل تريد اختيار فندق محدد؟ (اختياري)\n\nاختر من القائمة أو اضغط «لا يهم».",
        "hotel_any": "✔️ لا يهم / دع الموظف يقترح",
        "a_hotel_sel": "الفندق المختار",
        "done": (
            "✅ تم استلام طلبك!\n\nشكراً لك! سيتواصل معك فريق حجاز قريباً ويجيب على جميع أسئلتك.\n\n💰 سيخبرك موظفنا بالسعر والتفاصيل الكاملة شخصياً.\n⏱ نرد عادة خلال ساعة واحدة (في ساعات العمل).\n\nشكراً لصبرك! 🕋"
        ),
        "contact_txt": "📞 تواصل مع حجاز\n\nتواصل معنا عبر الأزرار أدناه. سيجيب فريقنا على أسئلتك.",
        "btn_call": "📞 اتصل",
        "btn_tg": "✈️ تيليجرام",
        "btn_wa": "💬 واتساب",
        "btn_ig": "📷 إنستغرام",
        "info_txt": (
            "ℹ️ *عن حجاز*\n\n"
            "حجاز — حجز فنادق موثوق وخدمة نقل في مكة والمدينة.\n\n"
            "• فنادق قرب الحرم\n• نقل من المطار وبين المدن\n"
            "• تنظيم الزيارات\n• أسعار مناسبة\n\n"
            "اضغط 🏨 لتقديم طلب."
        ),
        "choose_lang": "Tilni tanlang / Выберите язык / Choose language:",
        "invalid_num": "الرجاء إدخال رقم.",
        "back": "⬅️ رجوع",
        "a_new": "🔔 طلب جديد",
        "a_type": "النوع",
        "a_hotel": "فندق",
        "a_transfer": "نقل",
        "a_city": "المدينة",
        "a_stars": "الفئة",
        "a_meal": "الوجبات",
        "a_guests": "النزلاء",
        "a_dates": "التواريخ",
        "a_budget": "الميزانية",
        "a_trtype": "نوع النقل",
        "a_route": "المسار",
        "a_pax": "الركاب",
        "a_phone": "الهاتف",
        "a_name": "الاسم",
        "a_lang": "اللغة",
        "a_user": "المستخدم",
        "nights": "ليالٍ",
    },
    # ==================== TÜRKÇE ====================
    "tr": {
        "lang_name": "🇹🇷 Türkçe",
        "welcome": (
            "🕋 *HIJAZ — Suudi Arabistan Otel Rezervasyonu*\n\n"
            "Esselamu aleykum! Mekke ve Medine'de otel rezervasyonu ve "
            "transfer hizmeti için talep bırakın.\n\n"
            "Aşağıdan seçin 👇"
        ),
        "menu_booking": "🏨 Rezervasyon talebi",
        "menu_contact": "📞 İletişim",
        "menu_info": "ℹ️ Bilgi",
        "menu_lang": "🌐 Dili değiştir",
        "choose_service": "Neye ihtiyacınız var?",
        "svc_hotel": "🏨 Otel",
        "svc_transfer": "🚗 Transfer",
        "svc_both": "🏨+🚗 İkisi",
        "choose_city": "Hangi şehir?",
        "city_makkah": "🕋 Mekke",
        "city_madinah": "🕌 Medine",
        "city_both": "İkisi",
        "hotel_stars": "Otel kategorisi?",
        "stars_any": "Farketmez",
        "meal": "Yemek tipi?",
        "meal_ro": "Sadece konaklama",
        "meal_bb": "Kahvaltı dahil",
        "meal_hb": "Yarım pansiyon",
        "meal_fb": "Tam pansiyon",
        "guests": "Kaç kişi? (sayı girin)",
        "room_count": "Kaç oda gerekli? (sayı)",
        "room_type": "Oda tipi (kaç kişilik)?",
        "rt_single": "Tek (1)",
        "rt_double": "Çift (2)",
        "rt_triple": "Üç (3)",
        "rt_quad": "Dört (4)",
        "rt_mixed": "Karışık / farketmez",
        "a_rooms": "Oda sayısı",
        "a_roomtype": "Oda tipi",
        "checkin": "Giriş tarihi? (örn: 15/08/2026)",
        "mk_checkin": "🕋 MEKKE — giriş tarihi? (örn: 15/08/2026)",
        "mk_checkout": "🕋 MEKKE — çıkış tarihi? (örn: 18/08/2026)",
        "md_checkin": "🕌 MEDİNE — giriş tarihi? (örn: 18/08/2026)",
        "md_checkout": "🕌 MEDİNE — çıkış tarihi? (örn: 21/08/2026)",
        "a_mk_dates": "Mekke tarihleri",
        "a_md_dates": "Medine tarihleri",
        "checkout": "Çıkış tarihi? (örn: 18/08/2026)",
        "budget": "Bütçe (gecelik, $)? Bilmiyorsanız 'Atla' basın",
        "skip": "Atla",
        "transfer_type": "Transfer tipi?",
        "tr_airport": "✈️ Havalimanı ↔ otel",
        "tr_intercity": "🚙 Şehirlerarası (Mekke ↔ Medine)",
        "tr_ziyorat": "🕌 Ziyaret / gezi",
        "transfer_route": "Güzergahı yazın (örn: Cidde havalimanı → Mekke)",
        "transfer_date": "Transfer tarihi? (örn: 15/08/2026)",
        "pax": "Kaç yolcu? (sayı)",
        "phone": "📱 Telefon numaranız? (butona basın veya yazın)",
        "phone_btn": "📱 Numarayı gönder",
        "name": "Adınız?",
                "confirm_title": "📋 Talebinizi kontrol edin:",
        "confirm_ask": "Her şey doğru mu?",
        "btn_confirm": "✅ Onayla",
        "btn_cancel": "❌ İptal",
        "cancelled": "❌ Talep iptal edildi. Yeniden başlamak için menüyü kullanın.",
        "c_service": "Hizmet",
        "c_hotel": "Otel",
        "c_transfer": "Transfer",
        "req_no": "Talep numarası",
        "route_other": "✏️ Diğer (kendim yazacağım)",
        "transfer_route_manual": "Güzergahı yazın (örn: Cidde havalimanı → Mekke otel):",
        "car_q": "🚗 Hangi araç lazım? (isteğe bağlı)\n\nSeçin veya «Fark etmez» e basın — operatörümüz uygun aracı seçecek.",
        "car_any": "✔️ Fark etmez / operatör seçsin",
        "a_car": "Araç",
        "hotel_q": "🏨 Belirli bir otel seçmek ister misiniz? (isteğe bağlı)\n\nListeden seçin veya «Fark etmez» e basın.",
        "hotel_any": "✔️ Fark etmez / operatör önersin",
        "a_hotel_sel": "Seçilen otel",
        "done": (
            "✅ Talebiniz alındı!\n\nTeşekkürler! HIJAZ ekibi yakında sizinle iletişime geçecek ve tüm sorularınızı yanıtlayacak.\n\n💰 Fiyat ve tüm detayları operatörümüz bizzat bildirecek.\n⏱ Genellikle 1 saat içinde yanıt veriyoruz (çalışma saatlerinde).\n\nSabrınız için teşekkürler! 🕋"
        ),
        "contact_txt": "📞 HIJAZ ile iletişim\n\nAşağıdaki butonlarla bize ulaşın. Ekibimiz sorularınızı yanıtlayacak.",
        "btn_call": "📞 Ara",
        "btn_tg": "✈️ Telegram",
        "btn_wa": "💬 WhatsApp",
        "btn_ig": "📷 Instagram",
        "info_txt": (
            "ℹ️ *HIJAZ Hakkında*\n\n"
            "HIJAZ — Mekke ve Medine'de güvenilir otel rezervasyonu ve transfer.\n\n"
            "• Harem'e yakın oteller\n• Havalimanı ve şehirlerarası transfer\n"
            "• Ziyaret organizasyonu\n• Uygun fiyatlar\n\n"
            "Talep için 🏨 basın."
        ),
        "choose_lang": "Tilni tanlang / Выберите язык / Choose language:",
        "invalid_num": "Lütfen bir sayı girin.",
        "back": "⬅️ Geri",
        "a_new": "🔔 YENİ TALEP",
        "a_type": "Tür",
        "a_hotel": "Otel",
        "a_transfer": "Transfer",
        "a_city": "Şehir",
        "a_stars": "Kategori",
        "a_meal": "Yemek",
        "a_guests": "Misafirler",
        "a_dates": "Tarihler",
        "a_budget": "Bütçe",
        "a_trtype": "Transfer tipi",
        "a_route": "Güzergah",
        "a_pax": "Yolcular",
        "a_phone": "Telefon",
        "a_name": "İsim",
        "a_lang": "Dil",
        "a_user": "Kullanıcı",
        "nights": "gece",
    },
}


def t(lang, key):
    """Tarjima olish. Til topilmasa o'zbekcha qaytaradi."""
    return TR.get(lang, TR["uz"]).get(key, TR["uz"].get(key, key))
